allow_all_origins: false
allow_origins:
  - "*"
allow_methods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
  - HEAD
  - OPTIONS
allow_headers:
  - Origin
  - Content-Length
  - Content-Type
allow_credentials: false
expose_headers:
max_age: 12h
allow_wildcard: false
allow_browser_extensions: false
allow_web_sockets: false
allow_files: false