// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID    int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title *string `gorm:"column:title;type:varchar(32)" json:"title"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
