// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameArticleTag = "article_tags"

// ArticleTag mapped from table <article_tags>
type ArticleTag struct {
	TagID     int32 `gorm:"column:tag_id;type:int unsigned;primaryKey" json:"tag_id"`
	ArticleID int32 `gorm:"column:article_id;type:int unsigned;primaryKey;index:fk_article_tags_article,priority:1" json:"article_id"`
}

// TableName ArticleTag's table name
func (*ArticleTag) TableName() string {
	return TableNameArticleTag
}
