// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID   int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name *string `gorm:"column:name;type:varchar(32)" json:"name"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
