// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID      int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"` // ID
	Name    string `gorm:"column:name;type:varchar(32);not null" json:"name"`          // 名称
	Pwd     string `gorm:"column:pwd;type:varchar(32);not null" json:"pwd"`            // 密码
	Created int32  `gorm:"column:created;type:int;not null" json:"created"`            // 创建时间
	Updated int32  `gorm:"column:updated;type:int;not null" json:"updated"`            // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
